name: Build and Deploy Node.js App with Web Interface

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

  # Step 1: Checkout do repositório
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Configurando Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Exibir versão do Node e npm
    - name: Show Node.js and npm version
      run: |
        node -v
        npm -v

    # Step 4: Instalar dependências
    - name: Install dependencies
      run: npm install

    # Step 5: Verificar se há arquivos sensíveis
    - name: Check for .env or sensitive files
      run: |
        if [ -f .env ]; then
          echo ".env file exists. Remove it before pushing to public repo."
          exit 1
        else
          echo "No sensitive files found."
        fi

    # Step 6: Rodar testes automatizados
    - name: Run tests
      run: npm test

    # Step 7: Verificar lint (mesmo que simples)
    - name: Run Lint (optional)
      run: |
        echo "Simulando lint..."
        echo "Tudo limpo."

    # Step 8: Build da aplicação (simples, se necessário)
    - name: Build application
      run: |
        echo "No build step required for static files, skipping."

    # Step 9: Deploy no servidor
    - name: Deploy to Server
      run: |
        echo "Deploying to the server..."
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_SERVER }} 'bash -s' < ./deploy.sh

    # Step 10: Verificação final do deploy
    - name: Verify deployment
      run: |
        echo "Verifying deployment..."
        curl -f http://$DEPLOY_SERVER:3000 || exit 1
